version: '3'
services:
  golang:
    build: .
    image: golang:1.13
    volumes:
      - .:/go/src/app
    environment:
      - ADYEN_USERNAME=${ADYEN_USERNAME}
      - ADYEN_PASSWORD=${ADYEN_PASSWORD}
      - ADYEN_CLIENT_TOKEN=${ADYEN_CLIENT_TOKEN}
      - ADYEN_ACCOUNT=${ADYEN_ACCOUNT}
      - ADYEN_HMAC=${ADYEN_HMAC}
      - ADYEN_SKINCODE=${ADYEN_SKINCODE}
      - ADYEN_SHOPPER_LOCALE=${ADYEN_SHOPPER_LOCALE}
    ports:
      - 8080:8080